qiuzhiquan/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

qiuzhiquan/qiuzhiquan/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from interview.views import InterListView, InterDetailView, RegView, LoginView, LogoutView, IndexView, AddCommentView, \
    ContactView, FaqView
from qiuzhiquan.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),

    path('interlist/', InterListView.as_view(), name="interlist"),  # 名企面经映射
    path('ueditor/', include('DjangoUeditor.urls')),  # 增加ueditor映射
    path('register/', RegView.as_view(), name="register"),  # 用户注册映射
    path('login/', LoginView.as_view(), name="login"),  # 用户登录映射
    path('logout/', LogoutView.as_view(), name="logout"),  # 用户注销映射
    path('contact/', ContactView.as_view(), name="contact"),  # 联系页面的映射
    path('faq/', FaqView.as_view(), name="faq"),  # 问答页面的映射
    path('', IndexView.as_view(), name="index"),  # 首页映射
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),  # 管理媒体文件路径和处理模块
    re_path(r'^addcomment/(?P<interview_id>\d+)/$', AddCommentView.as_view(), name="addcomment"),  # 评论映射
    re_path(r'^interdetail/(?P<interview_id>\d+)/$', InterDetailView.as_view(), name="interdetail"),  # 面经详情映射
]

# 404和500配置
handler404 = 'interview.views.view_404'
handler500 = 'interview.views.view_500'

qiuzhiquan/interview/models.py
# _*_coding:utf8_*_
import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from DjangoUeditor.models import UEditorField


# Create your models here.
class User(AbstractUser):  # class User(models.Model):
    """
    用户表
    """
    # username = models.CharField(verbose_name="姓名", max_length=50)
    # email = models.CharField(verbose_name="邮箱", max_length=50)
    # password = models.CharField(verbose_name="密码", max_length=128)
    mobile = models.CharField(verbose_name="手机号码", max_length=11, blank=True, null=True)
    birthday = models.DateField(verbose_name="生日", blank=True, null=True)
    gen = (
        ("male", "男"),
        ("female", "女")
    )
    gender = models.CharField(verbose_name="性别", choices=gen, default="male", max_length=10)
    image = models.ImageField(verbose_name="头像", upload_to="users/%Y/%m", blank=True, null=True)

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Author(models.Model):
    """
    作者表
    """
    name = models.CharField(verbose_name="姓名", max_length=50)
    desc = models.TextField(verbose_name="简介")
    profession = models.CharField(verbose_name="专业", max_length=50)
    years = (
        ("1", "2018届"),
        ("2", "2017届"),
        ("3", "2016届"),
        ("4", "2015届"),
    )
    year = models.CharField(verbose_name="年级", choices=years, max_length=50)

    class Meta:
        verbose_name = "作者"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Interview(models.Model):
    """
    面经表
    """
    title = models.CharField(verbose_name="文章标题", max_length=50)
    desc = models.CharField(verbose_name="描述", max_length=100)
    # content = models.TextField(verbose_name="内容")
    content = UEditorField(verbose_name="内容", width=700, height=200, default="",
                           imagePath="content/%(basename)s_%(datetime)s.%(extname)s",
                           filePath="content/%(basename)s_%(datetime)s.%(extname)s")
    # qiuzhiquan/media/content/1.jpg
    image = models.ImageField(verbose_name="封面", upload_to="interview/%Y/%m")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="所属作者")
    company = models.CharField(verbose_name="公司", max_length=50)
    trades = (
        ("t1", "互联网"),
        ("t2", "网络安全"),
        ("t3", "运营商"),
        ("t4", "银行"),
        ("t5", "集成商"),
        ("t6", "国企"),
        ("t7", "云计算"),
        ("t8", "其他"),
    )
    trade = models.CharField(verbose_name="行业", choices=trades, default="t1", max_length=10)
    locations = (
        ("l1", "北京"),
        ("l2", "上海"),
        ("l3", "广州"),
        ("l4", "深圳"),
        ("l5", "全国"),
        ("l6", "其他"),
    )
    location = models.CharField(verbose_name="地区", choices=locations, default="l1", max_length=10)
    pub_time = models.DateTimeField(verbose_name="发布时间", default=datetime.datetime.now())
    read_counts = models.IntegerField(verbose_name="阅读次数", default=0)

    class Meta:
        verbose_name = "面经"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    评论
    """
    comment = models.CharField(verbose_name="评论", max_length=100)
    pub_time = models.DateTimeField(verbose_name="发布时间", default=datetime.datetime.now())
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE, verbose_name="文章外键")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户外键")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name


class Faq(models.Model):
    """
    常见问题
    """
    question = models.CharField(verbose_name="问题", max_length=100, default="")
    answer = models.TextField(verbose_name="回答", max_length=500, default="")
    image = models.ImageField(verbose_name="问答图片", upload_to="faq/%Y/%m", blank=True, null=True)

    class Meta:
        verbose_name = "问答"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.question

qiuzhiquan/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}DreamHLZ - 模板文件 {% endblock %}</title>

    <!-- 加载CSS脚本 -->
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    {% block css %}{% endblock %}


</head>

<body>
    {% block banner %}
    <!-- 导航栏 -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}"><i class="fa fa-spinner fa-spin fa-fw"></i>&nbsp; IT校招求职圈</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active" >
                        <a href="{% url 'index' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp;首页</a>
                    </li>
                    <li>
                        <a href="{% url 'interlist' %}"><i class="fa fa-book fa-fw" aria-hidden="true"></i>&nbsp;名企面经</a>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-weixin" aria-hidden="true"></i>&nbsp;大神分享<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">在线分享会</a>
                            </li>
                            <li>
                                <a href="#">大神面对面</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-dribbble" aria-hidden="true"></i>&nbsp;技术博文<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="active">
                                <a href="#">Python</a>
                            </li>
                            <li>
                                <a href="#">Django</a>
                            </li>
                            <li>
                                <a href="#">Security</a>
                            </li>
                        </ul>
                    </li>

                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dot-circle-o" aria-hidden="true"></i> {{ request.user.username }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'logout' %}">注销</a>
                            </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-cog fa-fw" aria-hidden="true"></i>&nbsp; 加入<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'login' %}">登录</a>
                                <a href="{% url 'register' %}">注册</a>
                            </li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    <!-- Content 内容区 -->
    {% block content %}
    {% endblock %}

    {% block footer %}
    <!-- 页脚 -->
    <div class="footor" style="background-color: #222">
        <span style="line-height:60px;color:#fff;padding-left:65px">Copyright &copy; 2013-2017 DreamHLZ 版权所有
        </span>
        <span style="line-height:60px;color:#fff;float:right;padding-right:65px">
            <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i>&nbsp;<a style="color: #ffffff " href="{% url 'contact' %}">联系我们</a>
        </span>
        <span style="line-height:60px;color:#fff;float:right;padding-right:50px">
            <i class="fa fa-question-circle fa-lg" aria-hidden="true"></i>&nbsp;<a style="color: #ffffff " href="{% url 'faq' %}">常见问题</a>
        </span>
        <span style="line-height:60px;color:#fff;float:right;padding-right:50px">
            <i class="fa fa-weibo fa-lg"></i>&nbsp;<a style="color: #ffffff " href="">新浪微博</a>
        </span>
    </div>
    {% endblock %}
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 3000 //changes the speed
    })
    </script>

    {% block js %}
        <script src="{% static 'js/jquery.goup.min.js' %}"></script>
        <script type="text/javascript">
        $(document).ready(function () {
            $.goup({
                trigger: 50,
                bottomOffset: 60,
                locationOffset: 20,
                title: '',
                titleAsText: true
            });
        });
    </script>
    {% endblock %}
</body>
</html>

qiuzhiquan/templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}联系我们 - IT校招求职圈{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">联系我们
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}">首页</a>
                    </li>
                    <li class="active">联系</li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <!-- 百度地图  -->
                <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                        src="https://j.map.baidu.com/Pzc4O"></iframe>
            </div>
            <div class="col-md-4">
                <h2>CONTACT US</h2>
                <p><i class="fa fa-weixin fa-lg"></i>
                    微信公众号: 开源学习手扎 </p>
                <p><i class="fa fa-phone fa-lg"></i>
                    电话: 183****0211,136****0903</p>
                <p><i class="fa fa-envelope-o fa-lg"></i>
                    邮箱: <a href="">zhaofeifeioo@gmail.com</a>
                </p>
                <p><i class="fa fa-clock-o fa-lg"></i>
                    咨询: 周一~五 早上9:00 - 下午 6:00 </p>
                <p><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i>
                    地址: 山西省太原市中北大学</p>
            </div>
        </div>
    <hr>
    </div>
{% endblock %}

qiuzhiquan/templates/faq.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}常见问题 - IT校招求职圈{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">常见问题
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}">首页</a>
                    </li>
                    <li class="active">常见问题</li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel-group" id="accordion">
                    {% for faq in all_faqs %}
                        {% if faq.id == 1 %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                            {{ faq.question }}</a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        {{ faq.answer }}
                                    </div>
                                </div>
                            </div>
                        {% elif faq.id == 2 %}
                                 <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                                {{ faq.question }}
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseTwo" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            {{ faq.answer }}
                                        </div>
                                    </div>
                                </div>
                        {% elif faq.id == 3 %}
                                 <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                                                {{ faq.question }}
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseThree" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            {{ faq.answer }}
                                        </div>
                                    </div>
                                </div>
                        {% elif faq.id == 4 %}
                                 <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                                                {{ faq.question }}
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseFour" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            {{ faq.answer }}
                                        </div>
                                    </div>
                                </div>
                         {% elif faq.id == 5 %}
                                 <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
                                                {{ faq.question }}
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseFive" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            {{ faq.answer }}
                                        </div>
                                    </div>
                                </div>
{#                         {% elif faq.id == 6 %}#}
{#                                 <div class="panel panel-default">#}
{#                                    <div class="panel-heading">#}
{#                                        <h4 class="panel-title">#}
{#                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSix">#}
{#                                                {{ faq.question }}#}
{#                                            </a>#}
{#                                        </h4>#}
{#                                    </div>#}
{#                                    <div id="collapseSix" class="panel-collapse collapse">#}
{#                                        <div class="panel-body">#}
{#                                            {{ faq.answer }}#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                         {% elif faq.id == 7 %}#}
{#                                 <div class="panel panel-default">#}
{#                                    <div class="panel-heading">#}
{#                                        <h4 class="panel-title">#}
{#                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">#}
{#                                                {{ faq.question }}#}
{#                                            </a>#}
{#                                        </h4>#}
{#                                    </div>#}
{#                                    <div id="collapseSeven" class="panel-collapse collapse">#}
{#                                        <div class="panel-body">#}
{#                                            {{ faq.answer }}#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                         {% elif faq.id == 8 %}#}
{#                                 <div class="panel panel-default">#}
{#                                    <div class="panel-heading">#}
{#                                        <h4 class="panel-title">#}
{#                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEight">#}
{#                                                {{ faq.question }}#}
{#                                            </a>#}
{#                                        </h4>#}
{#                                    </div>#}
{#                                    <div id="collapseEight" class="panel-collapse collapse">#}
{#                                        <div class="panel-body">#}
{#                                            {{ faq.answer }}#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

qiuzhiquan/templates/interview_detail.html
{% extends "interview_list.html" %}
{% load staticfiles %}
{% block title %}面经详情 - IT校招求职圈{% endblock %}

{% block content %}
    <div class="container">
    <!-- 面包屑导航 -->

        <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ interview.title }}
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'interlist' %}">名企面经</a>
                        </li>
                        <li class="active">面经详情</li>
                    </ol>
                </div>
            </div>

    <!-- 左边内容区域 -->

        <div class="col-lg-8">

                    <p><i class="fa fa-clock-o"></i>发表于 {{ interview.pub_time }}&nbsp;&nbsp; 阅读次数{{ interview.read_counts }}</p>
                    <hr>
                    <img class="img-responsive" src="{{ MEDIA_URL }}{{ interview.image }}" alt="{{ MEDIA_URL }}{{ interview.image }}">
                    <hr>

                    <!-- 面经正文-->
                    {% autoescape off %}
                    <p>
                        {{ interview.content }}
                    </p>
                    {% endautoescape %}
                    <hr>

                    <!-- 评论框-->
                    <div class="well">
                        <h4>说点什么吧:</h4>
                        <form role="form" method="post" action="{% url 'addcomment' interview.id %}">
                            <div class="form-group">
                                <textarea name="comment" class="form-control" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">提交</button>
                        {% csrf_token %}
                        </form>
                    </div>
                    <hr>

                    <!-- 评论内容 -->
                    {% for comment in comments %}
                     <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="http://placehold.it/64x64" alt="">
                        </a>
                        <div class="media-body">
                            <h5 class="media-heading">{{ comment.user.image }}
                                {{ comment.user.username }}
                                <small>{{ comment.pub_time }}</small>
                            </h5>
                            {{ comment.comment }}
                        </div>
                    </div>
                    {% endfor %}
                <hr>
                </div>


    <!-- 右边内容区域 -->
        <div class="col-md-4">
            <div class="well">
                <h4>作者简介</h4>
                <p>{{ interview.author.desc }}</p>
            </div>

            <div class="well">
                <h4>相关推荐</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                            {% for recommended_interview in recommended_interviews %}
                            <li>
                                <a href="{% url 'interdetail' recommended_interview.id %}">{{ recommended_interview.title | slice:":15" | add:"...   "}}</a>
                                &nbsp;&nbsp;<i class="fa fa-eye"></i>&nbsp;&nbsp;阅读次数{{ recommended_interview.read_counts }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="well">
                <h4>更多推荐</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                            {% for recommended_interview2 in recommended_interviews2 %}
                            <li>
                                <a href="{% url 'interdetail' recommended_interview2.id %}">{{ recommended_interview2.title | slice:":15" | add:"...   "}}</a>
                                &nbsp;&nbsp;<i class="fa fa-eye"></i>&nbsp;&nbsp;阅读次数{{ recommended_interview2.read_counts }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

qiuzhiquan/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>用户登录</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <style>
        body {
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #eee;
        }

        .form-signin {
          max-width: 330px;
          padding: 15px;
          margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
          margin-bottom: 10px;
        }
        .form-signin .checkbox {
          font-weight: normal;
        }
        .form-signin .form-control {
          position: relative;
          height: auto;
          -webkit-box-sizing: border-box;
             -moz-box-sizing: border-box;
                  box-sizing: border-box;
          padding: 10px;
          font-size: 16px;
        }
        .form-signin .form-control:focus {
          z-index: 2;
        }
        .form-signin input[type="email"] {
          margin-bottom: -1px;
          border-bottom-right-radius: 0;
          border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
          margin-bottom: 10px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
        }
    </style>

</head>


<body>
    <!-- 用户登录表单 -->
    <div class="container">
      <form class="form-signin" action="{% url 'login' %}" method="post" autocomplete="off">
        <h2 class="form-signin-heading">用户登录</h2>
        <label for="inputEmail" class="sr-only">邮箱</label>
        <input type="email" id="inputEmail" name="email" class="form-control" placeholder="请输入您的邮箱" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="请输入您的密码" required>
        <p style="color: red"> {{ error }}</p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">提交</button>
      {% csrf_token %}
      </form>
    </div>

</body>
</html>